name: expense_tracker
description: A Flutter application to track expenses using Firebase.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.0

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7

  # Local notifications
  flutter_local_notifications: ^19.2.0
  flutter_local_notifications_linux: ^6.0.0

  # Timezone support for scheduling
  timezone: ^0.10.0

  # Formatting dates
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
