name: expense_tracker_fixed
description: A Flutter application to track expenses using Firebase.
publish_to: 'none' # Remove this line if you intend to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0" # Cập nhật SDK constraint cho phiên bản Flutter mới hơn
  flutter: ">=3.10.0" # Cân nhắc nâng cấp phiên bản Flutter tối thiểu nếu có thể

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Hỗ trợ đa ngôn ngữ
    sdk: flutter

  cupertino_icons: ^1.0.6 # Phiên bản mới nhất (kiểm tra pub.dev)
  provider: ^6.1.2 # Phiên bản mới nhất (kiểm tra pub.dev)

  # Firebase
  firebase_core: ^3.13.0 # Phiên bản mới nhất (kiểm tra pub.dev)
  firebase_auth: ^5.5.3 # Phiên bản mới nhất (kiểm tra pub.dev)
  cloud_firestore: ^5.6.7 # Phiên bản mới nhất (kiểm tra pub.dev)

  # Local notifications (Kiểm tra lại sự cần thiết và phiên bản)
  # Nếu không dùng Linux, có thể bỏ flutter_local_notifications_linux
  flutter_local_notifications: ^19.2.0 # Phiên bản mới nhất (kiểm tra pub.dev)
  # flutter_local_notifications_linux: ^4.0.0 # Phiên bản mới nhất (kiểm tra pub.dev)

  # Timezone support for scheduling
  # timezone: ^0.9.2 # Phiên bản mới nhất (kiểm tra pub.dev) - Đã được thay thế bằng intl

  # Formatting dates and numbers
  intl: ^0.19.0 # Giữ nguyên hoặc cập nhật nếu có phiên bản mới hơn ổn định

  # fl_chart for bar, line, and pie charts
  fl_chart: ^0.68.0 # Giữ nguyên hoặc cập nhật

  # Shared Preferences
  shared_preferences: ^2.2.3 # Phiên bản mới nhất (kiểm tra pub.dev)

  # Google Fonts
  google_fonts: ^6.2.1 # Phiên bản mới nhất (kiểm tra pub.dev)

  # Collection package
  collection: ^1.18.0 # Giữ nguyên

  # Table Calendar (THÊM VÀO DỰA TRÊN MÃ NGUỒN history_screen.dart)
  table_calendar: ^3.1.0 # Phiên bản mới nhất (kiểm tra pub.dev)


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Phiên bản mới nhất (kiểm tra pub.dev)

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
